# Create a valid person
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Josenaldo Matos",
    "number": "999-999999"
}

###

# Try to create a person without a number will return a 400 HTTP code
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Josenaldo Matos"
}

###

# Try to create a person without a name will return a 400 HTTP code
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "number": "11-99999-9999"
}


###

# Use a invalid number: less than 8 characters
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Josenaldo Matos",
    "number": "99999"
}

###

# Use a invalid number: no dash character
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Josenaldo Matos",
    "number": "123456789"
}